//go:build !ignore_autogenerated

// Hand-written deepcopy (equivalent to controller-gen output) so the API types
// satisfy runtime.Object without a code-generation step in this repo.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *CostSource) DeepCopyInto(out *CostSource) {
	*out = *in
}

func (in *CostSource) DeepCopy() *CostSource {
	if in == nil {
		return nil
	}
	out := new(CostSource)
	in.DeepCopyInto(out)
	return out
}

func (in *LLMCostBudget) DeepCopyInto(out *LLMCostBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *LLMCostBudget) DeepCopy() *LLMCostBudget {
	if in == nil {
		return nil
	}
	out := new(LLMCostBudget)
	in.DeepCopyInto(out)
	return out
}

func (in *LLMCostBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LLMCostBudgetList) DeepCopyInto(out *LLMCostBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]LLMCostBudget, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *LLMCostBudgetList) DeepCopy() *LLMCostBudgetList {
	if in == nil {
		return nil
	}
	out := new(LLMCostBudgetList)
	in.DeepCopyInto(out)
	return out
}

func (in *LLMCostBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *LLMCostBudgetSpec) DeepCopyInto(out *LLMCostBudgetSpec) {
	*out = *in
	out.CostSource = in.CostSource
}

func (in *LLMCostBudgetSpec) DeepCopy() *LLMCostBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(LLMCostBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *LLMCostBudgetStatus) DeepCopyInto(out *LLMCostBudgetStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *LLMCostBudgetStatus) DeepCopy() *LLMCostBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(LLMCostBudgetStatus)
	in.DeepCopyInto(out)
	return out
}
